USE [master]
GO
/****** Object:  Database [Website_BanTraSua]    Script Date: 10/27/2025 8:47:00 PM ******/
CREATE DATABASE [Website_BanTraSua]
 CONTAINMENT = NONE
 
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Website_BanTraSua].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Website_BanTraSua] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET ARITHABORT OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Website_BanTraSua] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Website_BanTraSua] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Website_BanTraSua] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Website_BanTraSua] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET RECOVERY FULL 
GO
ALTER DATABASE [Website_BanTraSua] SET  MULTI_USER 
GO
ALTER DATABASE [Website_BanTraSua] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Website_BanTraSua] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Website_BanTraSua] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Website_BanTraSua] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Website_BanTraSua] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Website_BanTraSua] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Website_BanTraSua', N'ON'
GO
ALTER DATABASE [Website_BanTraSua] SET QUERY_STORE = ON
GO
ALTER DATABASE [Website_BanTraSua] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Website_BanTraSua]
GO
/****** Object:  Table [dbo].[CTDonHang]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTDonHang](
	[MaCT] [int] IDENTITY(1,1) NOT NULL,
	[MaDH] [int] NOT NULL,
	[MaBT] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [decimal](10, 2) NOT NULL,
	[GiamGiaDong] [decimal](10, 2) NOT NULL,
	[ThanhTien] [decimal](10, 2) NOT NULL,
	[GhiChu] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DonHang]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DonHang](
	[MaDH] [int] IDENTITY(1,1) NOT NULL,
	[MaKH] [int] NOT NULL,
	[MaNV] [int] NULL,
	[MaKM] [int] NULL,
	[NgayLap] [datetime2](7) NOT NULL,
	[TrangThaiDonHang] [nvarchar](30) NOT NULL,
	[PaymentStatus] [nvarchar](30) NOT NULL,
	[PaymentMethod] [nvarchar](50) NULL,
	[PaidAt] [datetime2](7) NULL,
	[TongHang] [decimal](12, 2) NOT NULL,
	[GiamGiaDon] [decimal](12, 2) NOT NULL,
	[PhiVanChuyen] [decimal](12, 2) NOT NULL,
	[TongThanhToan] [decimal](12, 2) NOT NULL,
	[GhiChu] [nvarchar](500) NULL,
	[PhuongThucNhanHang] [nvarchar](50) NULL,
	[DiaChiNhanHang] [nvarchar](max) NULL,
	[TenNguoiNhan] [nvarchar](50) NULL,
	[SDTNguoiNhan] [nchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[v_DonHang_TinhTong]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[v_DonHang_TinhTong]
AS
SELECT
    dh.MaDH,
    SUM(ct.ThanhTien) AS TongHangDong,
    dh.GiamGiaDon,
    dh.PhiVanChuyen,
    (SUM(ct.ThanhTien) - dh.GiamGiaDon + dh.PhiVanChuyen) AS TongPhaiTra
FROM dbo.DonHang dh
JOIN dbo.CTDonHang ct ON ct.MaDH = dh.MaDH
GROUP BY dh.MaDH, dh.GiamGiaDon, dh.PhiVanChuyen;
GO
/****** Object:  Table [dbo].[BienTheSanPham]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BienTheSanPham](
	[MaBT] [int] IDENTITY(1,1) NOT NULL,
	[MaSP] [int] NOT NULL,
	[MaSize] [int] NOT NULL,
	[GiaBan] [decimal](10, 2) NOT NULL,
	[TrangThai] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaBT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_BienThe_Unique] UNIQUE NONCLUSTERED 
(
	[MaSP] ASC,
	[MaSize] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CTDonHang_Topping]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CTDonHang_Topping](
	[MaCT] [int] NOT NULL,
	[MaTopping] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [decimal](10, 2) NOT NULL,
	[ThanhTien] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCT] ASC,
	[MaTopping] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhGia]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhGia](
	[MaDG] [int] IDENTITY(1,1) NOT NULL,
	[MaKH] [int] NOT NULL,
	[MaCT] [int] NOT NULL,
	[SoSao] [int] NOT NULL,
	[BinhLuan] [nvarchar](max) NULL,
	[NgayDG] [datetime2](7) NOT NULL,
	[TraLoiAdmin] [nvarchar](max) NULL,
	[TraLoiLuc] [datetime2](7) NULL,
	[TraLoiBoi] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_DanhGia_OnePerLine] UNIQUE NONCLUSTERED 
(
	[MaKH] ASC,
	[MaCT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DanhMucSanPham]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanhMucSanPham](
	[MaDM] [int] IDENTITY(1,1) NOT NULL,
	[TenDM] [nvarchar](255) NOT NULL,
	[MoTa] [nvarchar](max) NULL,
	[DeletedAt] [datetime2](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaDM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenDM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GioHang]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GioHang](
	[MaGH] [int] IDENTITY(1,1) NOT NULL,
	[MaKH] [int] NOT NULL,
	[TrangThai] [nvarchar](20) NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaGH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GioHangCT]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GioHangCT](
	[MaCTGH] [int] IDENTITY(1,1) NOT NULL,
	[MaGH] [int] NOT NULL,
	[MaBT] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [decimal](10, 2) NOT NULL,
	[ThanhTien] [decimal](10, 2) NOT NULL,
	[GhiChu] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCTGH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GioHangCT_Topping]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GioHangCT_Topping](
	[MaCTGH] [int] NOT NULL,
	[MaTopping] [int] NOT NULL,
	[SoLuong] [int] NOT NULL,
	[DonGia] [decimal](10, 2) NOT NULL,
	[ThanhTien] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaCTGH] ASC,
	[MaTopping] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhachHang]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhachHang](
	[MaKH] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[MatKhauHash] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[TenKH] [nvarchar](255) NOT NULL,
	[SoDienThoai] [nvarchar](20) NULL,
	[TrangThai] [tinyint] NOT NULL,
	[AnhDaiDien] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SoDienThoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KhuyenMaiSanPham]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KhuyenMaiSanPham](
	[MaKM] [int] NOT NULL,
	[MaSP] [int] NOT NULL,
	[PhanTramGiam] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaKM] ASC,
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NhanVien]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NhanVien](
	[MaNV] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[MatKhauHash] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[TenNV] [nvarchar](255) NOT NULL,
	[VaiTro] [tinyint] NOT NULL,
	[SoDienThoai] [nvarchar](20) NULL,
	[TrangThai] [tinyint] NOT NULL,
	[AnhDaiDien] [nvarchar](500) NULL,
	[DeletedAt] [datetime2](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[SoDienThoai] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OtpCodes]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OtpCodes](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[KhachHangId] [int] NOT NULL,
	[Code] [varchar](10) NOT NULL,
	[Type] [varchar](30) NOT NULL,
	[ExpiresAt] [datetime] NOT NULL,
	[UsedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductMedia]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductMedia](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[IsPrimary] [bit] NULL,
	[Url] [varchar](255) NOT NULL,
	[ProductId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SanPham]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SanPham](
	[MaSP] [int] IDENTITY(1,1) NOT NULL,
	[MaDM] [int] NOT NULL,
	[TenSP] [nvarchar](255) NOT NULL,
	[MoTa] [nvarchar](255) NULL,
	[TrangThai] [tinyint] NOT NULL,
	[UrlAnh] [varchar](255) NULL,
	[DeletedAt] [datetime2](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SizeSanPham]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SizeSanPham](
	[MaSize] [int] IDENTITY(1,1) NOT NULL,
	[TenSize] [nvarchar](10) NOT NULL,
	[TrangThai] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaSize] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenSize] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SuKienKhuyenMai]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SuKienKhuyenMai](
	[MaKM] [int] IDENTITY(1,1) NOT NULL,
	[TenSuKien] [nvarchar](255) NOT NULL,
	[MoTa] [nvarchar](255) NULL,
	[NgayBD] [date] NOT NULL,
	[NgayKT] [date] NOT NULL,
	[TrangThai] [tinyint] NOT NULL,
	[UrlAnh] [nvarchar](max) NULL,
	[LuotXem] [int] NULL,
	[DeletedAt] [datetime2](7) NULL,
 CONSTRAINT [PK__SuKienKh__2725CF15FA1FF15C] PRIMARY KEY CLUSTERED 
(
	[MaKM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topping]    Script Date: 10/27/2025 8:47:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topping](
	[MaTopping] [int] IDENTITY(1,1) NOT NULL,
	[TenTopping] [nvarchar](255) NOT NULL,
	[GiaThem] [decimal](10, 2) NOT NULL,
	[TrangThai] [tinyint] NOT NULL,
	[UrlAnh] [varchar](255) NULL,
	[DeletedAt] [datetime2](6) NULL,
PRIMARY KEY CLUSTERED 
(
	[MaTopping] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TenTopping] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [UX_GioHang_Active_OnePerKH]    Script Date: 10/27/2025 8:47:01 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_GioHang_Active_OnePerKH] ON [dbo].[GioHang]
(
	[MaKH] ASC
)
WHERE ([TrangThai]=N'ACTIVE')
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BienTheSanPham] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[CTDonHang] ADD  DEFAULT ((0)) FOR [GiamGiaDong]
GO
ALTER TABLE [dbo].[CTDonHang_Topping] ADD  DEFAULT ((1)) FOR [SoLuong]
GO
ALTER TABLE [dbo].[DanhGia] ADD  DEFAULT (sysutcdatetime()) FOR [NgayDG]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT (sysutcdatetime()) FOR [NgayLap]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT (N'ChoXuLy') FOR [TrangThaiDonHang]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT (N'ChuaThanhToan') FOR [PaymentStatus]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT ((0)) FOR [TongHang]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT ((0)) FOR [GiamGiaDon]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT ((0)) FOR [PhiVanChuyen]
GO
ALTER TABLE [dbo].[DonHang] ADD  DEFAULT ((0)) FOR [TongThanhToan]
GO
ALTER TABLE [dbo].[GioHang] ADD  DEFAULT (N'ACTIVE') FOR [TrangThai]
GO
ALTER TABLE [dbo].[GioHang] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[GioHang] ADD  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
GO
ALTER TABLE [dbo].[GioHangCT_Topping] ADD  DEFAULT ((1)) FOR [SoLuong]
GO
ALTER TABLE [dbo].[KhachHang] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[NhanVien] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[SanPham] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[SizeSanPham] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[SuKienKhuyenMai] ADD  CONSTRAINT [DF__SuKienKhu__Trang__5165187F]  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[Topping] ADD  DEFAULT ((1)) FOR [TrangThai]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [FK_BienThe_SanPham] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SanPham] ([MaSP])
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [FK_BienThe_SanPham]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD  CONSTRAINT [FK_BienThe_Size] FOREIGN KEY([MaSize])
REFERENCES [dbo].[SizeSanPham] ([MaSize])
GO
ALTER TABLE [dbo].[BienTheSanPham] CHECK CONSTRAINT [FK_BienThe_Size]
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD  CONSTRAINT [FK_CTDH_BT] FOREIGN KEY([MaBT])
REFERENCES [dbo].[BienTheSanPham] ([MaBT])
GO
ALTER TABLE [dbo].[CTDonHang] CHECK CONSTRAINT [FK_CTDH_BT]
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD  CONSTRAINT [FK_CTDH_DH] FOREIGN KEY([MaDH])
REFERENCES [dbo].[DonHang] ([MaDH])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CTDonHang] CHECK CONSTRAINT [FK_CTDH_DH]
GO
ALTER TABLE [dbo].[CTDonHang_Topping]  WITH CHECK ADD  CONSTRAINT [FK_CTDHT_CTDH] FOREIGN KEY([MaCT])
REFERENCES [dbo].[CTDonHang] ([MaCT])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CTDonHang_Topping] CHECK CONSTRAINT [FK_CTDHT_CTDH]
GO
ALTER TABLE [dbo].[CTDonHang_Topping]  WITH CHECK ADD  CONSTRAINT [FK_CTDHT_T] FOREIGN KEY([MaTopping])
REFERENCES [dbo].[Topping] ([MaTopping])
GO
ALTER TABLE [dbo].[CTDonHang_Topping] CHECK CONSTRAINT [FK_CTDHT_T]
GO
ALTER TABLE [dbo].[DanhGia]  WITH CHECK ADD  CONSTRAINT [FK_DG_CT] FOREIGN KEY([MaCT])
REFERENCES [dbo].[CTDonHang] ([MaCT])
GO
ALTER TABLE [dbo].[DanhGia] CHECK CONSTRAINT [FK_DG_CT]
GO
ALTER TABLE [dbo].[DanhGia]  WITH CHECK ADD  CONSTRAINT [FK_DG_KH] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KhachHang] ([MaKH])
GO
ALTER TABLE [dbo].[DanhGia] CHECK CONSTRAINT [FK_DG_KH]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DH_KH] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KhachHang] ([MaKH])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DH_KH]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DH_KM] FOREIGN KEY([MaKM])
REFERENCES [dbo].[SuKienKhuyenMai] ([MaKM])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DH_KM]
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD  CONSTRAINT [FK_DH_NV] FOREIGN KEY([MaNV])
REFERENCES [dbo].[NhanVien] ([MaNV])
GO
ALTER TABLE [dbo].[DonHang] CHECK CONSTRAINT [FK_DH_NV]
GO
ALTER TABLE [dbo].[GioHang]  WITH CHECK ADD  CONSTRAINT [FK_GH_KH] FOREIGN KEY([MaKH])
REFERENCES [dbo].[KhachHang] ([MaKH])
GO
ALTER TABLE [dbo].[GioHang] CHECK CONSTRAINT [FK_GH_KH]
GO
ALTER TABLE [dbo].[GioHangCT]  WITH CHECK ADD  CONSTRAINT [FK_GHCT_BT] FOREIGN KEY([MaBT])
REFERENCES [dbo].[BienTheSanPham] ([MaBT])
GO
ALTER TABLE [dbo].[GioHangCT] CHECK CONSTRAINT [FK_GHCT_BT]
GO
ALTER TABLE [dbo].[GioHangCT]  WITH CHECK ADD  CONSTRAINT [FK_GHCT_GH] FOREIGN KEY([MaGH])
REFERENCES [dbo].[GioHang] ([MaGH])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GioHangCT] CHECK CONSTRAINT [FK_GHCT_GH]
GO
ALTER TABLE [dbo].[GioHangCT_Topping]  WITH CHECK ADD  CONSTRAINT [FK_GHCTT_GHCT] FOREIGN KEY([MaCTGH])
REFERENCES [dbo].[GioHangCT] ([MaCTGH])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[GioHangCT_Topping] CHECK CONSTRAINT [FK_GHCTT_GHCT]
GO
ALTER TABLE [dbo].[GioHangCT_Topping]  WITH CHECK ADD  CONSTRAINT [FK_GHCTT_T] FOREIGN KEY([MaTopping])
REFERENCES [dbo].[Topping] ([MaTopping])
GO
ALTER TABLE [dbo].[GioHangCT_Topping] CHECK CONSTRAINT [FK_GHCTT_T]
GO
ALTER TABLE [dbo].[KhuyenMaiSanPham]  WITH CHECK ADD  CONSTRAINT [FK_KMSP_KM] FOREIGN KEY([MaKM])
REFERENCES [dbo].[SuKienKhuyenMai] ([MaKM])
GO
ALTER TABLE [dbo].[KhuyenMaiSanPham] CHECK CONSTRAINT [FK_KMSP_KM]
GO
ALTER TABLE [dbo].[KhuyenMaiSanPham]  WITH CHECK ADD  CONSTRAINT [FK_KMSP_SP] FOREIGN KEY([MaSP])
REFERENCES [dbo].[SanPham] ([MaSP])
GO
ALTER TABLE [dbo].[KhuyenMaiSanPham] CHECK CONSTRAINT [FK_KMSP_SP]
GO
ALTER TABLE [dbo].[OtpCodes]  WITH CHECK ADD FOREIGN KEY([KhachHangId])
REFERENCES [dbo].[KhachHang] ([MaKH])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ProductMedia]  WITH CHECK ADD  CONSTRAINT [FKja8o0hbvf4ugyqx0rc4xkm9h5] FOREIGN KEY([ProductId])
REFERENCES [dbo].[SanPham] ([MaSP])
GO
ALTER TABLE [dbo].[ProductMedia] CHECK CONSTRAINT [FKja8o0hbvf4ugyqx0rc4xkm9h5]
GO
ALTER TABLE [dbo].[SanPham]  WITH CHECK ADD  CONSTRAINT [FK_SanPham_DanhMuc] FOREIGN KEY([MaDM])
REFERENCES [dbo].[DanhMucSanPham] ([MaDM])
GO
ALTER TABLE [dbo].[SanPham] CHECK CONSTRAINT [FK_SanPham_DanhMuc]
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD CHECK  (([GiaBan]>(0)))
GO
ALTER TABLE [dbo].[BienTheSanPham]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD CHECK  (([GiamGiaDong]>=(0)))
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[CTDonHang]  WITH CHECK ADD CHECK  (([ThanhTien]>=(0)))
GO
ALTER TABLE [dbo].[CTDonHang_Topping]  WITH CHECK ADD CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[CTDonHang_Topping]  WITH CHECK ADD CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[CTDonHang_Topping]  WITH CHECK ADD CHECK  (([ThanhTien]>=(0)))
GO
ALTER TABLE [dbo].[DanhGia]  WITH CHECK ADD CHECK  (([SoSao]>=(1) AND [SoSao]<=(5)))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([GiamGiaDon]>=(0)))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([PaymentStatus]=N'DaThanhToan' OR [PaymentStatus]=N'ChuaThanhToan'))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([PhiVanChuyen]>=(0)))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([TongHang]>=(0)))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([TongThanhToan]>=(0)))
GO
ALTER TABLE [dbo].[DonHang]  WITH CHECK ADD CHECK  (([TrangThaiDonHang]=N'DaHuy' OR [TrangThaiDonHang]=N'DaGiao' OR [TrangThaiDonHang]=N'DangGiao' OR [TrangThaiDonHang]=N'DangPhaChe' OR [TrangThaiDonHang]=N'ChoXuLy'))
GO
ALTER TABLE [dbo].[GioHang]  WITH CHECK ADD CHECK  (([TrangThai]=N'CANCELLED' OR [TrangThai]=N'CHECKED_OUT' OR [TrangThai]=N'ACTIVE'))
GO
ALTER TABLE [dbo].[GioHangCT]  WITH CHECK ADD CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[GioHangCT]  WITH CHECK ADD CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[GioHangCT]  WITH CHECK ADD CHECK  (([ThanhTien]>=(0)))
GO
ALTER TABLE [dbo].[GioHangCT_Topping]  WITH CHECK ADD CHECK  (([DonGia]>=(0)))
GO
ALTER TABLE [dbo].[GioHangCT_Topping]  WITH CHECK ADD CHECK  (([SoLuong]>(0)))
GO
ALTER TABLE [dbo].[GioHangCT_Topping]  WITH CHECK ADD CHECK  (([ThanhTien]>=(0)))
GO
ALTER TABLE [dbo].[KhachHang]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[KhuyenMaiSanPham]  WITH CHECK ADD CHECK  (([PhanTramGiam]>=(1) AND [PhanTramGiam]<=(100)))
GO
ALTER TABLE [dbo].[NhanVien]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[NhanVien]  WITH CHECK ADD  CONSTRAINT [CK_NhanVien_VaiTro] CHECK  (([VaiTro]=(3) OR [VaiTro]=(2) OR [VaiTro]=(1)))
GO
ALTER TABLE [dbo].[NhanVien] CHECK CONSTRAINT [CK_NhanVien_VaiTro]
GO
ALTER TABLE [dbo].[SanPham]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[SizeSanPham]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[SuKienKhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK__SuKienKhu__Trang__52593CB8] CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
ALTER TABLE [dbo].[SuKienKhuyenMai] CHECK CONSTRAINT [CK__SuKienKhu__Trang__52593CB8]
GO
ALTER TABLE [dbo].[SuKienKhuyenMai]  WITH CHECK ADD  CONSTRAINT [CK_KM_Ngay] CHECK  (([NgayKT]>=[NgayBD]))
GO
ALTER TABLE [dbo].[SuKienKhuyenMai] CHECK CONSTRAINT [CK_KM_Ngay]
GO
ALTER TABLE [dbo].[Topping]  WITH CHECK ADD CHECK  (([GiaThem]>=(0)))
GO
ALTER TABLE [dbo].[Topping]  WITH CHECK ADD CHECK  (([TrangThai]=(1) OR [TrangThai]=(0)))
GO
USE [master]
GO
ALTER DATABASE [Website_BanTraSua] SET  READ_WRITE 
GO
